security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_RESPONSIBLE: ROLE_USER
        ROLE_ADMIN: ROLE_RESPONSIBLE

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        # Registration
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # Site
        - { path: ^/requests/new, role: ROLE_USER }
        - { path: ^/requests/delete, role: ROLE_USER }
        
        - { path: new, role: ROLE_RESPONSIBLE }
        - { path: copy, role: ROLE_RESPONSIBLE }
        - { path: edit, role: ROLE_RESPONSIBLE }
        
        - { path: ^/, role: ROLE_USER }
        
        # Admin
        - { path: user, role: ROLE_SUPER_ADMIN }
        - { path: delete, role: ROLE_SUPER_ADMIN }
        
        - { path: ^/admin/, role: ROLE_ADMIN }